import type { Metadata } from "next";
import AuthImage  from '../../../public/assets/kf-auth.svg'
import Image from "next/image";

export const metadata: Metadata = {
  title: "Keshflip Pay ",
  description: "Generated by Redwan Null",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
            <div className="grid min-h-svh lg:grid-cols-2">
                    {children}
                    <div className="relative hidden  lg:block p-8 ">
                        <div className="w-full h-full flex flex-col items-center justify-between">
                            <Image src={AuthImage} alt="expImage"  width={650} height={600}/>
                        </div>
                    </div>
                </div>
    </main>
  );
}
